<?php

namespace Blutch\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookGenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookGenreRepository extends EntityRepository {

	public function getBookGenres() {
		$query = $this->createQueryBuilder("g")
			->orderBy("g.description", "ASC")
			->getQuery();
		
		return $query->getResult();
	}
	
	public function getBookGenre($id) {
		$query = $this->createQueryBuilder("g")
			->leftJoin("g.books", "b")
			->addSelect("b")
			->where("g.id = :id")
			->setParameter("id", $id)
			->orderBy("g.description", "ASC")
			->getQuery();
		
		return $query->getSingleResult();
	}

}
