<?php

namespace Blutch\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository {
	
	public function getBooks() {
		$query = $this->createQueryBuilder("b")
			->leftJoin("b.author", "a")
			->addSelect("a")
			->leftJoin("b.bookGenres", "g")
			->addSelect("g")
			->orderBy("b.title", "ASC")
			->getQuery();
		
		return $query->getResult();
	}
	
	public function getBook($id) {
		$query = $this->createQueryBuilder("b")
			->leftJoin("b.author", "a")
			->addSelect("a")
			->where("b.id = :id")
			->setParameter("id", $id)
			->getQuery();
		
		return $query->getOneOrNullResult();
	}
	
}
